### ISSUE TITLE
Conflict with podio.com

### ISSUE THREAD

**Issue by lajlev** [tsenart/sight#29]
It adds 

``` css
    body {font-family: Inconsolata}
```

Pretty fucked up
http://img.laj.lv/3e14402s2M0n1v2G1L0n

I thought I was hacked :)
